# Generated by Django 2.2 on 2019-04-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visit',
            field=models.IntegerField(default=0),
        ),
    ]
