# Generated by Django 2.2 on 2019-05-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190508_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='decription',
            field=models.CharField(default='Описание еще не добавлено!', max_length=400),
        ),
    ]
