# Generated by Django 2.2 on 2019-05-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_decription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='decription',
        ),
    ]
